/// Matrix Market (.mtx) format serialization support.
module Yog.IO.MatrixMarket

open System
open Yog.Model

type MatrixMarketHeader =
    { Format: string
      Field: string
      Symmetry: string }

type MatrixMarketSize = { Rows: int; Cols: int; Entries: int }

type MatrixMarketWarning =
    | InvalidEdgeLine of string
    | IncompleteComplexLine of string
    | EdgeAddFailed of string * string

type MatrixMarketResult<'n, 'e> =
    { Graph: Graph<'n, 'e>
      Warnings: MatrixMarketWarning list }

type MatrixMarketError =
    | EmptyInput
    | InvalidHeader of string
    | MissingHeader of string
    | InvalidSizeLine of string
    | UnexpectedEndOfFile

type MatrixMarketOptions<'e> =
    { WeightFormatter: 'e -> string
      NodeFormatter: NodeId -> string
      EdgeFormatter: string -> string }

let defaultOptions: MatrixMarketOptions<'e> =
    { WeightFormatter = (fun w -> w.ToString())
      NodeFormatter = (fun id -> id.ToString())
      EdgeFormatter = id }

let optionsWith (weightFormatter: 'e -> string) =
    { WeightFormatter = weightFormatter
      NodeFormatter = (fun id -> id.ToString())
      EdgeFormatter = id }

let serializeWith (options: MatrixMarketOptions<'e>) (graph: Graph<'n, 'e>) : string =
    let nodeCount = order graph
    let edges = allEdges graph
    let edgeCount = edges.Length
    let symmetry = if graph.Kind = Directed then "general" else "symmetric"

    let header = sprintf "%%%%MatrixMarket matrix coordinate real %s\n" symmetry
    let comment = "% Generated by Yog\n"
    let sizeLine = sprintf "%d %d %d\n" nodeCount nodeCount edgeCount

    let dataLines =
        edges
        |> List.map (fun (fromId, toId, weight) ->
            let wStr = options.WeightFormatter weight
            sprintf "%s %s %s" (options.NodeFormatter fromId) (options.NodeFormatter toId) (options.EdgeFormatter wStr))
        |> String.concat "\n"

    header + comment + sizeLine + dataLines + "\n"

let serialize (graph: Graph<'n, 'e>) : string = serializeWith defaultOptions graph

let private parseHeaderLine (line: string) : Result<MatrixMarketHeader, MatrixMarketError> =
    let trimmed = line.Trim()

    if trimmed.StartsWith("%%MatrixMarket") then
        let parts = trimmed.Split([| ' '; '\t' |], StringSplitOptions.RemoveEmptyEntries)

        match parts with
        | [| "%%MatrixMarket"; "matrix"; format; field; symmetry |] ->
            Ok
                { Format = format
                  Field = field
                  Symmetry = symmetry }
        | _ -> Error(InvalidHeader line)
    else
        Error(MissingHeader line)

let rec private parseSize (lines: string list) : Result<MatrixMarketSize * string list, MatrixMarketError> =
    match lines with
    | [] -> Error UnexpectedEndOfFile
    | line :: rest ->
        let trimmed = line.Trim()

        if trimmed = "" || trimmed.StartsWith("%") then
            parseSize rest
        else
            let parts = trimmed.Split([| ' '; '\t' |], StringSplitOptions.RemoveEmptyEntries)

            match parts with
            | [| rowsStr; colsStr; entriesStr |] ->
                match Int32.TryParse(rowsStr), Int32.TryParse(colsStr), Int32.TryParse(entriesStr) with
                | (true, r), (true, c), (true, e) -> Ok({ Rows = r; Cols = c; Entries = e }, rest)
                | _ -> Error(InvalidSizeLine line)
            | _ -> Error(InvalidSizeLine line)

let parseWith
    (input: string)
    (gType: GraphType option)
    (nodeParser: NodeId -> 'n)
    (edgeParser: obj -> 'e)
    : Result<MatrixMarketResult<'n, 'e>, MatrixMarketError> =

    if String.IsNullOrWhiteSpace(input) then
        Error EmptyInput
    else
        let lines = input.Split([| '\r'; '\n' |], StringSplitOptions.None) |> Array.toList

        match lines with
        | [] -> Error EmptyInput
        | headerLine :: rest ->
            match parseHeaderLine headerLine with
            | Error e -> Error e
            | Ok header ->
                match parseSize rest with
                | Error e -> Error e
                | Ok(size, edgeLines) ->
                    let finalType =
                        match gType with
                        | Some t -> t
                        | None ->
                            if
                                header.Symmetry = "symmetric"
                                || header.Symmetry = "skew-symmetric"
                                || header.Symmetry = "hermitian"
                            then
                                Undirected
                            else
                                Directed

                    let mutable graph = empty finalType
                    let maxNode = max size.Rows size.Cols

                    for id in 1..maxNode do
                        graph <- addNode id (nodeParser id) graph

                    let mutable warnings = []

                    let parseEdgeValue
                        (field: string)
                        (weightParts: string list)
                        (line: string)
                        : Result<obj, MatrixMarketWarning> =
                        match field, weightParts with
                        | "pattern", _ -> Ok(1.0 :> obj)
                        | "real", w :: _ ->
                            match Double.TryParse(w) with
                            | true, f -> Ok(f :> obj)
                            | false, _ -> Error(InvalidEdgeLine line)
                        | "integer", w :: _ ->
                            match Int32.TryParse(w) with
                            | true, i -> Ok(i :> obj)
                            | false, _ -> Error(InvalidEdgeLine line)
                        | "complex", r :: i :: _ ->
                            match Double.TryParse(r), Double.TryParse(i) with
                            | (true, rv), (true, iv) -> Ok((rv, iv) :> obj)
                            | _ -> Error(InvalidEdgeLine line)
                        | "complex", _ -> Error(IncompleteComplexLine line)
                        | _, w :: _ -> Ok(w :> obj)
                        | _ -> Ok(1.0 :> obj)

                    for line in edgeLines do
                        let trimmed = line.Trim()

                        if trimmed <> "" && not (trimmed.StartsWith("%")) then
                            let parts =
                                trimmed.Split([| ' '; '\t' |], StringSplitOptions.RemoveEmptyEntries)
                                |> Array.toList

                            match parts with
                            | fromStr :: toStr :: weightParts ->
                                match Int32.TryParse(fromStr), Int32.TryParse(toStr) with
                                | (true, fromId), (true, toId) ->
                                    match parseEdgeValue header.Field weightParts trimmed with
                                    | Ok valObj ->
                                        let weight = edgeParser valObj

                                        try
                                            graph <- addEdge fromId toId weight graph
                                        with ex ->
                                            warnings <- EdgeAddFailed(ex.Message, trimmed) :: warnings
                                    | Error w -> warnings <- w :: warnings
                                | _ -> warnings <- InvalidEdgeLine trimmed :: warnings
                            | _ -> warnings <- InvalidEdgeLine trimmed :: warnings

                    Ok
                        { Graph = graph
                          Warnings = List.rev warnings }

let parse (input: string) (gType: GraphType option) : Result<MatrixMarketResult<unit, float>, MatrixMarketError> =
    parseWith input gType (fun _ -> ()) (fun obj ->
        match obj with
        | :? float as f -> f
        | :? int as i -> float i
        | _ -> 1.0)
